name: do_so_655
description: A powerful Flutter application for lottery number scanning, analysis, and prediction for Vietlott. This app provides various features including traditional number scanning, input-based number scanning from the database, statistical charting, predictive analysis, comprehensive number scanning, and many other advanced functionalities. It is designed to help users efficiently track, analyze, and predict lottery results.
publish_to: 'googlePlay'


version: 1.0.3+3

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  charts_flutter: ^0.12.0
  flutter_typeahead: ^4.6.1
  connectivity: ^3.0.6
  ml_linalg: ^13.11.31
  dio: ^5.3.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/logo.png
    - assets/images/Lotto Screen.png
    - assets/images/period.jpg
    - assets/images/chart.jpg
    - assets/images/checking.jpg
    - assets/images/result_checking.jpg
    - assets/images/checking_all.jpg
    - assets/images/result_checking_all.jpg
    - assets/images/prediction.jpg
    - assets/images/jackpotwin.png
    - assets/images/Power655.png
    
  uses-material-design: true

